### ISSUE TITLE
[Bug] prop-types missing in dependencies

### ISSUE THREAD

**Issue by onichandame** [storybookjs/storybook-addon-console#49]
### Describe the bug

This addon requires `prop-types` as a direct dependency, but does not declare it in either dependencies or peerDependencies. A quick search in issues does not give me any result.

### Steps to reproduce the behavior

1. create a project using yarn v2 pnp
2. add storybook and this addon
3. run storybook to see the error

### Expected behavior

no error

### Screenshots and/or logs

![无标题](https://user-images.githubusercontent.com/23728505/132192199-bcaea471-e424-4b34-89f2-4db7863af535.png)

### Environment

N/A

### Additional context

N/A

### Workaround

in yarnrc.yml

```yaml
packageExtensions:
  "@storybook/addon-console@*":
    dependencies:
      prop-types: "*"
```
